src/seq/aminoacid.jl, src/seq/aminoacidsequence.jl, src/seq/geneticcode.jl, src/seq/kmer.jl, src/seq/nucleotide.jl, src/seq/nucleotidecounts.jl, src/seq/nucleotidesequence.jl, src/seq/seq.jl, test/seq/test_seq.jl
Here is a list of what I did:
* Split the code in several files (#28)
* Changed many function definitions to one-liners
* `nucleotide_count` was changed to the contructor `NucleotideCounts`
* Implemented (badly) a `NucleotideCounts` method for K-mers (+ Tests)
* Solved  bugs (including ones with constructors, string decorators)
* Simplified nucleotide's `show()`
* Changed print formatting of sequences
* Improved commenting
=> RFC: [Seq] Code refactor and bug solving

test/seq/test_seq.jl
Added tests for sequence length, sequence access (iterations and out of bounds access), creation of empty sequences and creation of subsequence from ranges.
I hope the coverage goes up a little bit with this PR.
=> Added 26 tests for Nucleotide Sequences

src/seq/geneticcode.jl, src/seq/nucleotide.jl, src/seq/seq.jl, test/seq/test_seq.jl
Added some more tests for nucleotides, nucleotide sequences and k-mers and solved a bug with the function `rnakmer(seq::RNASequence)`. I also modified the organization of the tests, with more contexts and sub-contexts (I believe it's more clear when the tests run). As of now, I don't expect to see coverage going up a lot.
I'll add some more tests later this week.
=> [Seq] More tests, less bugs

REQUIRE, src/Bio.jl, src/ragel.jl, src/seq/Makefile, src/seq/alphabet.jl, src/seq/aminoacid.jl, src/seq/fasta.jl, src/seq/fasta.rl, src/seq/fastq.jl, src/seq/fastq.rl, src/seq/nucleotide.jl, src/seq/quality.jl, src/seq/seq.jl, test/REQUIRE, test/seq/test_seq.jl
Not ready for review yet, but follow along and comment if interested.
Notable features:
* Parser are generated with ragel (specifically, [my fork of ragel](https://github.com/dcjones/ragel)).
* `ragel.jl` defines some types and macros to factor out the tricky parts: which is mainly parsing a buffered stream as a opposed to reading everything into memory before parsing, which we obviously want to avoid.
* Regular files are memory mapped by default. Potentially that can lead to speed up in some cases, but I need to do some benchmarking to see.
You can see the example FASTA parser I have in `fasta.rl`. It's pretty simple to define once you wrap your head around ragel, and pretty fast (about 9 seconds to parse the human genome from a fasta file with 40% cpu utilization, indicating that it's …
=> WIP: Parsing infastructure

REQUIRE, src/seq/aminoacid.jl, src/seq/nucleotide.jl, src/seq/seq.jl, test/seq/test_seq.jl
This adds a concatenation constructor for sequence types, like
```julia
julia> DNASequence(dna"ACGTACGT", dna"TTTTTTTT", dna"TCGATCGA")
24nt DNA Sequence
ACGTACGTTTTTTTTTTCGATCGA
```
=> Concatenation for sequence types.

src/seq/aminoacid.jl, src/seq/nucleotide.jl, src/seq/seq.jl, src/seq/util.jl
Start writing more documentation to Seq module
=> [Seq] More documentation

CONTRIBUTING.md
Adds a CONTRIBUTING.md file with a basic style guide, etc. See #46.
=> Add a basic CONTRIBUTING.md

test/intervals/test_intervals.jl, test/seq/test_seq.jl
Update to the new syntax required by FactCheck
=> New FactCheck syntax (=> / -->)

src/seq/fastq.jl, src/seq/fastq.rl, src/seq/quality.jl, test/seq/test_seq.jl
NB: this is work in progress
Hi all,
As discussed on gitter, I've implemented a function to write a FASTQ record to an IO stream. I imagine that it could be implemented better, including using some functionality from `quality.jl` to do the quality string conversion.
Also, I'd assume a FASTA writer would come in handy.
Let me know what you think! I'm still not very experienced w/ Julia, so any and all criticism is welcome :)
Cheers,
Kevin
=> Writing of FASTQ sequences

src/seq/nucleotide.jl, test/seq/test_seq.jl
This will fix the problem of #82
=> Fix subseq

.travis.yml, README.md
Codecov has some nice features that coveralls does not, so we might as well use both.
=> Add Codecov support.

test/seq/TestSeq.jl
Making the PR just to test this change. Merging as soon as tests pass.
=> Test show method for RNA nucleotides

src/align/anchors.jl, test/align/TestAlign.jl
I think this is a typo. Please merge this if so, @dcjones.
=> fix printing of anchor

.travis.yml, docs/make.jl, docs/mkdocs.yml, docs/src/man/contributing.md
https://github.com/MichaelHatherly/Documenter.jl/issues/1
=> Rename Lapidary to Documenter.

docs/mkdocs.yml, docs/src/index.md, docs/src/man/structure.md, src/structure/model.jl, src/structure/pdb.jl, src/structure/spatial.jl
Hi all,
This PR adds documentation for `Bio.Structure` in the Lapidary.jl format. It also expands a few in-code docs.
Let me know if it looks okay. Thanks,
Joe
=> Documentation for Bio.Structure

src/seq/bioseq.jl, src/seq/kmer.jl, test/seq/runtests.jl
This adds the `findnext` method.
=> add Base.findnext for BioSequence

docs/src/index.md, docs/src/man/tools.md
Documentation for the blast command line wrapper. Please let me know if I should add anything else.
=> add documentation for blast module

.gitignore
- Cloned BioFmtSpecimens (created under test/ by test suite)
- KDE directory files
- Vim swap & misc temp files
=> Add a bunch of temp files to gitignore

REQUIRE, src/Ragel.jl, src/intervals/bigbed.jl, src/seq/fasta.jl, src/seq/fasta.rl, src/seq/fastq.jl, src/seq/fastq.rl
This will fix #159 after https://github.com/BioJulia/BufferedStreams.jl/pull/11 and https://github.com/BioJulia/Libz.jl/pull/21. So, we need to tag and release new versions of BufferedStreams.jl and Libz.jl to make TravisCI happy.
=> fix BigBed parser

test/runtests.jl, test/util/indexing.jl, test/util/runtests.jl, test/util/windows.jl
This is to fix issue #174. The test/runtests.jl file wasn't reading in test files for util folder correctly. Tests worked on the 161 branch so something must have gone awry during the merge/rebase.
=> Fix for 161 error.

docs/src/index.md, docs/src/lib/seq.md, docs/src/man/alignments.md, docs/src/man/intervals.md, docs/src/man/seq.md, docs/src/man/structure.md, docs/src/man/tools.md
See https://github.com/MichaelHatherly/Documenter.jl/pull/51 for details.
=> Updates for Documenter.jl syntax changes

REQUIRE, src/Bio.jl, src/phylo/Phylo.jl, src/phylo/branch_basics.jl, src/phylo/manipulation.jl, src/phylo/node_basics.jl, src/phylo/phylogeny.jl, src/util/indexing.jl, src/util/tokenize.jl, src/util/windows.jl, test/phylo/runtests.jl, test/util/indexing.jl
Ok, here we have a rework of Phylo to build on top of recent advances in graph packages in Julia - In particular LightGraphs.jl.
The graph types do the job of encoding the structure of the phylogeny, whilst our phylogeny types do the job of encoding the extra information phylogenies require, and make it easy for people to manipulate them.
=> Phylo Rework

src/phylo/Phylo.jl, src/phylo/branch_basics.jl, src/phylo/manipulation.jl, src/phylo/node_basics.jl, src/phylo/phylogeny.jl, test/phylo/runtests.jl
Lets bump up the test coverage for Phylo!
=> Added more tests for phylogeny types.

docs/src/man/seq.md, src/seq/Seq.jl, src/seq/bioseq.jl, src/seq/kmer.jl, src/seq/search/approx.jl, src/seq/search/exact.jl, test/seq/runtests.jl
This is the second search tool I mentioned in #152. This allows approximate sequence searching up to `k` errors with an bit-parallel algorithm.
=> Approximate search/rsearch for sequences.

docs/src/man/tools.md, src/tools/blast/BLAST.jl, src/tools/blast/README.md, src/tools/blast/blastcommandline.jl, test/tools/runtests.jl
Renamed `BlastResult` -> `BLASTResult`.
=> rename Blast to BLAST (take 2)

src/seq/kmer.jl, test/seq/runtests.jl
I've forgot to include this in #202. I will merge this soon if Travis CI says okay on v0.4.
=> define eltype for KmerNeighborIterator (and add tests)

src/Bio.jl, src/IO.jl, src/Ragel.jl, src/intervals/Intervals.jl, src/intervals/bed-parser.jl, src/intervals/bed-parser.rl, src/intervals/bed.jl, src/phylo/Phylo.jl, src/seq/Seq.jl, src/seq/bioseq.jl, src/seq/fasta-parser.jl, src/seq/fasta-parser.rl, src/seq/fasta.jl, src/seq/fastq-parser.jl, src/seq/fastq-parser.rl, src/seq/fastq.jl, src/seq/quality.jl, src/seq/seqrecord.jl, src/structure/Structure.jl, src/structure/pdb.jl, test/seq/runtests.jl
This implements writers for FASTA and FASTQ (ref: #208).
=> Writer interfaces for FASTA and FASTQ file formats.

src/util/windows.jl, test/util/windows.jl
This modifies the code for sliding windows slightly, such that in a for loop now you get a tuple of values. The first value is the start and end position of the window, and the second value is the view of the sequence / array itself in that region.
=> Sliding windows return their start and ends.

src/intervals/strand.jl, test/intervals/runtests.jl
I will merge this soon because this is a tiny improvement.
=> add convert(Char, ::Strand)

src/seq/bioseq.jl, src/seq/kmer.jl, test/seq/runtests.jl
Mostly stylistic changes of `mismatches` and other docstrings.
=> clean up mismatches and docs

src/seq/Seq.jl, src/seq/nucleotide.jl, src/seq/sequence.jl, test/seq/runtests.jl
This adds the `gc_content` function to calculate GC content of a sequence.
=> add gc_content

src/seq/bioseq.jl, test/seq/runtests.jl
These would be useful sometimes.
=> implement map and map! for BioSequence

src/seq/bioseq.jl, test/seq/runtests.jl
Like #226, I implemented `filter` and `filter!` for `BioSequence`.
=> implement filter and filter! for BioSequence

src/seq/Seq.jl, src/seq/twobit.jl, test/seq/runtests.jl
=> support .2bit format

src/align/pairwise/alignment.jl, test/align/runtests.jl
This closes #231.
@diegozea Is this a reasonable solution to your issue?
=> define ref2seq and seq2ref for PairwiseAlignment

REQUIRE, src/align/pairwise/alignment.jl, src/intervals/bigbed.jl, test/align/runtests.jl, test/tools/runtests.jl
This backports a few commits to the release-0.2 branch. After merging, I will tag and release v0.2.1 if no objections.
=> Backports for 0.2

src/seq/fai.jl, src/seq/fasta.jl, test/seq/runtests.jl
=> FASTA Index

docs/src/man/intervals.md
=> fix intervals.md

docs/src/man/intervals.md
Yet another fix of intervals.md.
=> fix a typo in intervals.md

test/seq/runtests.jl
so the file handle gets closed and the file can be cleaned up on Windows
=> open with a do block

docs/src/man/seq.md
Nothing complicated, just a small change to docs.
=> Added U for ambiguous nucleotides in Seq docs

REQUIRE, test/REQUIRE
Distributions.jl is required in src/phylo/dating.jl.
=> add Distributions.jl to REQUIRE

README.md
Furthur to @bicycle1885's changes, I forgot to ask for Bio.Phylo to be added!
Also propose adding header above badges.
=> Furthur readme edit

docs/src/man/var.md, src/seq/bioseq.jl, src/seq/sequence.jl, test/seq/runtests.jl
Implements #272 for Biological Sequences.
=> Added Base.parse for biological sequences

src/phylo/dating.jl
=> Edited dating.jl

src/seq/bioseq.jl
Before (master):
```
julia> seq = randdnaseq(100_000)
100000nt DNA Sequence:
TGAAGACATAACACGTGAGTGGGCAGGTGACACAGCACCGAGAG…AACCATCTGGACGGTAGACACGAGACATTAACCACTACTCTCTT
julia> @benchmark reverse($seq)
BenchmarkTools.Trial:
samples:          10000
evals/sample:     1
memory estimate:  48.94 kb
allocs estimate:  3
minimum time:     34.84 μs (0.00% GC)
median time:      37.50 μs (0.00% GC)
mean time:        47.93 μs (9.23% GC)
maximum time:     2.99 ms (95.88% GC)
julia> seq = randdnaseq(99_999)
99999nt DNA Sequence:
CACCCTCAGAAAGATGACCGAGTAGCGCAGTCGAAAAGAGTAGA…GGAACTAGTCAGCGATGCTAACGGTGCACTCTGTCAATCATTTG
julia> @benchmark reverse($seq)
BenchmarkTools.Trial:
samples:          10000
evals/sample:     1
memory tolerance: …
```
=> improve the performance of reverse nucleotide sequence

REQUIRE
I forgot to fix the requirement of Julia version in #220 .
=> fix Julia version requirement

docs/src/man/seq.md, src/seq/Seq.jl, src/seq/bioseq.jl, test/seq/runtests.jl
Following from discussion on #282, I've implemented methods for the creation of sequence-major and site-major matrices. Very useful for computing on multiple sequences sometimes.
=> Added sitemajor, seqmajor, docs, and tests

docs/src/man/reading.md, src/IO.jl, src/Ragel.jl, src/align/hts/bam/reader.jl, src/align/hts/sam/reader.jl, src/intervals/Intervals.jl, src/intervals/bed-parser.jl, src/intervals/bed-parser.rl, src/intervals/bed.jl, src/intervals/bigbed-parser.jl, src/intervals/bigbed-parser.rl, src/intervals/bigbed.jl, src/intervals/interval.jl, src/precompile.jl, src/seq/Seq.jl, src/seq/fasta-parser.jl, src/seq/fasta-parser.rl, src/seq/fasta.jl, src/seq/fastq-parser.jl, src/seq/fastq-parser.rl, src/seq/fastq.jl, src/seq/twobit.jl, src/structure/Structure.jl, test/seq/runtests.jl
=> rename parsers to readers

src/IO.jl, src/align/hts/bam/reader.jl, src/align/hts/bam/writer.jl, src/align/hts/sam/reader.jl, src/align/hts/sam/writer.jl, src/intervals/Intervals.jl, src/intervals/bed.jl, src/intervals/bigbed.jl, src/intervals/interval.jl, src/seq/Seq.jl, src/seq/fasta.jl, src/seq/fastq.jl, src/seq/twobit.jl
This implements the `Bio.IO.stream` function, which fixes a part of #288.
@kdmurray91, can you check if this solves the issue you mentioend?
=> add the Bio.IO.stream function

src/align/hts/bam/reader.jl, test/align/runtests.jl
This implements a missing piece of #265, and also is a part of #288.
=> implement open(::IO, BAM)

src/align/Align.jl, src/intervals/bed.jl
This removes an unknown exported function.
=> remove hasop export

src/align/hts/bam/reader.jl, test/align/runtests.jl
I forgot to implement  this method.
=> fix eltype for BAMReader

src/seq/fastq/reader.jl, src/seq/twobit/reader.jl, test/seq/runtests.jl
This will slightly improve the code coverage.
=> add more tests on Bio.Seq

docs/src/man/alignments.md, src/align/Align.jl, src/align/hts/bam/record.jl, src/align/hts/sam/record.jl, test/align/runtests.jl
This exports a hidden method for SAM/BAM records.
=> implement seqlength

test/tools/runtests.jl
https://github.com/JuliaLang/METADATA.jl/pull/6316
=> remove Compat from test/tools/runtests.jl

test/tools/runtests.jl
This is already merged to the master branch, but I'll kick CI in case.
=> remove Compat from test/tools/runtests.jl (#336)

docs/src/man/structure.md, src/structure/Structure.jl, src/structure/model.jl, src/structure/pdb.jl, src/structure/spatial.jl, test/structure/runtests.jl
This is a PR to improve the `Bio.Structure` module. Since I wrote it I have learned more about Julia, and thought a bit more about the implementation. There are some changes to the type system but the user-facing functions are all the same.
Some changes are implemented now, but when complete this PR will add:
- Significantly faster file parsing and much less memory allocation.
- Calculation of bond angles/dihedrals/Ramachandran plots.
- Calculation of contact maps.
- Getting sequence from the residues in a PDB file.
- More complete docs.
Still work and testing needed. Closes #151.
=> New features for Bio.Structure

src/seq/bioseq.jl, test/seq/runtests.jl
I ran into a couple bugs with sequences. Test cases to reproduce and fixes here.
=> Fix a couple BioSequence bugs

REQUIRE, src/seq/bioseq.jl, test/seq/runtests.jl, test/tools/runtests.jl
This backports a serious bug fix done in #344. After checking CI I'm going to tag a new bug fix release.
=> Backport #344

docs/src/man/seq.md, src/seq/bioseq.jl
Implements an alteration of non-standard string literals behaviour as highlighted in #348.
=> Fix of Non-standard string literals

src/seq/bioseq.jl, test/seq/runtests.jl
=> fix reverse(BioSequence)

src/seq/bioseq.jl, test/seq/runtests.jl
To fix #356. I'll tag v0.4.3 soon if no objections.
=> fix reverse(BioSequence) (#357)

README.md, docs/mkdocs.yml, docs/src/man/phylo.md, docs/src/man/var.md, src/phylo/dating.jl, src/phylo/phylogeny.jl
Some minor edits and changes to Phylo manual pages, before I start on new docs for the new branch metadata system.
=> Changes to Phylo documentation.

docs/src/man/var.md, src/var/mutation_counting.jl
Mainly regarding the rename of DifferentMutation to AnyMutation.
@Ward9250 Could you double check this?
Cheers,
K
=> Update documentation for Bio.Var

docs/src/man/var.md
Will merge this in a few hours if no objections.
=> Fix tiny typo introduced with #372

src/intervals/index/bgzfindex.jl, test/align/runtests.jl
=> fix linear index access of BAM

src/align/Align.jl, src/align/hts/bam/record.jl, src/align/hts/sam/record.jl, src/declare.jl, src/intervals/Intervals.jl, src/intervals/interval.jl, src/seq/Seq.jl, src/seq/seqrecord.jl, src/structure/Structure.jl, src/var/Var.jl
Continued from #379. This may still be an incomplete list of shared method names (if you find more, let me know 😅 ), but I think it's okay to move more names after merging this pull request.
=> list more method names in declare.jl

docs/src/man/alignments.md, docs/src/man/seq.md, docs/src/man/var.md, src/align/submat.jl, src/phylo/Phylo.jl, src/seq/Seq.jl, src/seq/alphabet.jl, src/seq/bioseq.jl, src/seq/composition.jl, src/seq/demultiplexer.jl, src/seq/deprecated.jl, src/seq/eachkmer.jl, src/seq/fastq/parser.jl, src/seq/fastq/parser.rl, src/seq/fastq/reader.jl, src/seq/geneticcode.jl, src/seq/kmer.jl, src/seq/nucleic_acids.jl, src/seq/nucleotide.jl, src/seq/randseq.jl, src/seq/refseq.jl, src/seq/search/re.jl, src/seq/sequence.jl, src/seq/twobit/writer.jl, src/util/windows.jl, src/var/distances.jl, src/var/mutation_counting.jl, test/align/runtests.jl, test/seq/runtests.jl
Implements renames as per #391.
=> Rename of DNANucleotide, RNANucleotide, Nucleotide

docs/src/man/seq.md, src/align/hts/sam/reader.jl, src/intervals/index/bgzfindex.jl, test/align/runtests.jl
Cherry-picked some commits for v0.4.4.
=> Release 0.4 (v0.4.4)

src/intervals/index/bgzfindex.jl
I'm going to merge and tag this soon once CI says okay because this patch is in urgent need.
=> Release v0.4.5

NEWS.md, README.md
Update README and NEWS I'm aware of.
=> update README and NEWS

src/var/vcf/header.jl, src/var/vcf/metainfo.jl, test/var/runtests.jl
Also, some docs and conversions from `AbstractString` and `Vector{UInt8}` to `VCFMetainfo` are added.
=> add more methods for VCFHeader like SAMHeader

src/Bio.jl, src/Exceptions.jl, src/var/Var.jl, src/var/vcf/record.jl, test/var/runtests.jl
=> VCF accessors

src/align/Align.jl, src/align/hts/sam/record.jl, src/declare.jl, src/var/vcf/record.jl, test/align/runtests.jl
=> revise SAM accessors

src/intervals/gff3/reader.jl
A minor tweak of the GFF3 reader.
=> escape only when a GFF3 record is in a target list

NEWS.md, src/StringFields.jl, src/intervals/interval.jl, src/intervals/intervalcollection.jl, src/intervals/intervalstream.jl, test/intervals/runtests.jl
=> use Base.isless to order sequence names by default

src/seq/Seq.jl, src/seq/fasta/fasta.jl
=> Add description() and identifier() to FASTA export

NEWS.md, docs/src/man/reading.md, src/seq/Seq.jl, src/seq/abif/abif.jl, src/seq/abif/reader.jl, test/seq/runtests.jl
Hello, it's my first contribution to BioJulia.
This PR implements a basic ABIF Reader based on [http://www6.appliedbiosystems.com/support/software_community/ABIF_File_Format.pdf](http://www6.appliedbiosystems.com/support/software_community/ABIF_File_Format.pdf)
I'm waiting for this PR ( BioJulia/BioFmtSpecimens#16 )
so I can commit the tests 
Let me know if there something to change
Example how it's works:
```julia
julia> using Bio.Seq
julia> abif = open(AbifReader, "310.ab1")
julia> getindex(abif, "PBAS")
Dict{String,String} with 2 entries:
"PBAS2" => "TGATNTTNACNNTTTTG.....
"PBAS1" => "TGATNTTNACNNTTTTG......
.........
julia> tags(abif)
113-element Array{Bio.Seq.ABIFDirEntry,1}:
Bio.Seq.ABIFDirEntry("AEPt",2,4,2,1,2,218563)
Bio.Seq.ABIFDirEntry("APXV",1,19,1,2,2,218591)
.....
julia> …
```
=> ABIF Reader

NEWS.md, src/seq/sequence.jl, test/seq/runtests.jl
=> do not print newlines in sequence

NEWS.md, docs/src/man/seq/sequences/kmer.md, src/seq/Seq.jl, src/seq/kmer.jl, test/seq/runtests.jl
Also adds documentation and a doctest.
=> Add @kmer_str macro to allow kmer string literals

src/intervals/gff3/gff3.jl, src/intervals/gff3/reader.jl, src/intervals/gff3/record.jl, test/intervals/runtests.jl
=> Fix UndefVarError in IntervalCollection(GFFReader)

docs/src/man/intervals.md
I had to read the tests & source to work out how to do it, so probably could use
a note in the docs...
Also do a few BEDReader -> BED.Reader conversions
=> Document GFF->IntervalCollection

src/intervals/interval.jl, test/intervals/runtests.jl
I always expect this to work but never succeeded. So, I added a new constructor.
=> add Interval(seqname, range) constructor

docs/src/man/structure.md, src/structure/spatial.jl, test/structure/runtests.jl
While using Bio.Structure for a project I found a use case for an indexed version for the `{omega,phi,psi}angle` functions.
=> Indexed versions of {omega,phi,psi}angle

.travis.yml, REQUIRE, appveyor.yml, test/TestFunctions.jl
Don't test on julia 0.5 anymore on master.
=> Update the CI
