BioJulia/Bio.jl

src/seq/nucleotide.jl
Has referred to the non-existing variable 'aa', should refer to the input 'nt'
=> Fix show methods for nucleotide input

src/seq/nucleotide.jl
which is a standard behavior of destructive functions
(cf. Base.push!, Base.append!, etc.)
=> make unsafe_complement! return a transformed sequence

src/seq/nucleotide.jl
Now a long sequence looks like:
=> fit sequence printing to the window size

src/seq/seq.jl, src/seq/util.jl
I believe this is cool:
1. Copy a sequence into your clipboard in REPL: `julia> genome[interval] |> clipboard`
2. Go to the BLAST/BLAT website and paste it in the web form.
3. Click a button.
4. Profit!
=> add the 'clipboard' methods for sequence types

src/seq/aminoacid.jl, src/seq/seq.jl, test/seq/test_seq.jl
We often use three-letter abbreviations to represent amino acids.
For example, Protein Data Bank (PDB) format adopts these three-letter encoding as its standard (http://www.wwpdb.org/documentation/file-format-content/format33/sect3.html#SEQRES).
This pull request implements a parser for one-letter and three-letter abbreviations which is case-insensitive and ignores white space.
=> add parse method for amino acids

src/intervals/interval.jl, src/intervals/intervals.jl, src/intervals/intervalstream.jl, test/intervals/test_intervals.jl
This adds a function `coverage` that will compute coverage over an `IntervalStream`. It works like the [`genomecov -bg`](http://bedtools.readthedocs.org/en/latest/content/tools/genomecov.html) command in bedtools.
Performance is really good compared to bedtools:
```bash
» wc -l motifs.bed
3272681 motifs.bed
» time bedtools genomecov -bg -i motifs.bed -g hg19.chromSizes > /dev/null
24.92s user 8.56s system 98% cpu 33.841 total
```
```julia
@time coverage(read("motifs.bed", BED))
7.922 seconds      (59164 k allocations: 2371 MB, 30.36% gc time)
```
I actually think ours can be significantly faster. The bottleneck is inserting intervals into an `IntervalCollection`, and that can be done faster with bulk insertion (i.e. collect all the intervals in an array and then insert in one go) which I …
=> [RFC] Interval Coverage

src/seq/nucleotide.jl
Somewhat surprisingly, inlining the `getnuc` method makes `getindex` ~6x faster.
script:
```julia
using Bio.Seq
function loop(seq)
x = zero(UInt)
for i in 1:endof(seq)
x += convert(UInt, seq[i])
end
x
end
let
fasta = shift!(ARGS)
for rec in read(fasta, FASTA)
println(@time loop(rec.seq))
end
end
```
input: chr1 of human
result:
```
Before:
11.008 seconds      (225 M allocations: 3438 MB, 2.02% gc time)
After:
1.674 seconds      (13866 allocations: 585 KB)
```
I cannot account for the huge memory allocations, but inlining diminishes this strange phenomenon.
There may be a bug in Julia.
---
```
julia> versioninfo()
Julia Version 0.4.0-dev+6350
Commit 9b14a7c* (2015-07-29 10:26 UTC)
Platform Info:
System: Darwin (x86_64-apple-darwin14.3.0)
CPU: Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz …
```
=> speed up the getindex method with inlining

src/seq/seq.jl
`import Base.Operators` has been removed in Julia: https://github.com/JuliaLang/julia/pull/12235.
So we have to import all operators explicitly from the `Base` module from now on.
This pull request adds missing operators to the import list.
=> import operators from Base explicitly

.travis.yml
If we decide to remove 0.3 from travis (See issue #71) , just merge this PR
=> Remove 0.3 from travis

src/seq/alphabet.jl
As suggested in #72 , hash values must be stable to precompile the Bio.Seq module.
This defines the `hash` function for `Alphabet` instead of initializing the `alphabet_type` global dictionary in `__init__()`.
=> define hash function for Alphabet to compile safely

src/seq/aminoacid.jl, src/seq/nucleotide.jl, test/seq/test_seq.jl
Sorry for mixing several topics in a pull request:
1. I often want to write sequences in a file or an interactive session with multiple lines literal, but `dna"..."` doesn't allow that. These newlines will be removed in this pull request.
2. I've found that `AminoAcidSequence` doesn't have the `==` method. I added it and some tests.
3. The unit test is failing due to the sequence parsing (or format specimens?). I hid them for a moment just because it was noisy.
@dcjones Could you fix the testing problem when you have time? I'm not perfectly sure what's going on here.
=> Remove newlines

src/seq/Seq.jl, test/seq/TestSeq.jl
We **REALLY** have to take the importing problem seriously.
This caused an error when printing a nucleotide:
```
julia> using Bio.Seq
julia> DNA_A
Error showing value of type Bio.Seq.DNANucleotide:
ERROR: MethodError: `write` has no method matching write(::Base.Terminals.TTYTerminal, ::Char)
you may have intended to import Base.write
Closest candidates are:
write(::IO, ::Bio.Seq.SeqRecord{Bio.Seq.NucleotideSequence{Bio.Seq.DNANucleotide},Bio.Seq.FASTQMetadata})
in show at /Users/kenta/.julia/v0.4/Bio/src/seq/nucleotide.jl:158
in anonymous at show.jl:1278
in with_output_limit at /usr/local/julia/v0.4/lib/julia/sys.dylib
in showlimited at show.jl:1277
in writemime at replutil.jl:4
in display at REPL.jl:115
in display at REPL.jl:118
[inlined code] from multimedia.jl:151
in display at …
```
=> import the write method into Bio.Seq from Base

src/StringFields.jl, src/seq/aminoacid.jl, src/seq/fasta.jl, src/seq/fasta.rl, src/seq/fastq.jl, src/seq/fastq.rl, src/seq/seqrecord.jl, test/intervals/TestIntervals.jl, test/seq/TestSeq.jl
This adds tests that reads examples, writes them, then reads them back. This tests that contents of what we are reading and writing is well-formed.
It also fixed a few things that were caught by these tests:
* Amino acid sequences were missing two residues when read from fasta.
* fasta and fastq files print trailing space when there is no description.
* Solexa fastq quality scores (which can be negative) were not encoded correctly when written.
=> Round trip tests for reading/writing. And some bug fixes.

src/Ragel.jl, src/intervals/bigbed.jl, src/intervals/interval.jl, src/intervals/intervalstream.jl, src/seq/aminoacid.jl, src/seq/nucleotide.jl, src/seq/util.jl, test/seq/TestSeq.jl
I defined the `convert` methods to byte sequences.
This would be useful in many ways: passing biological sequences to C libraries, allviating overhead of accessing packed nucleotides, and so on.
I think `DNASequence(seq::Union(Vector{Uint8}, String)) = NucleotideSequence(DNANucleotide, seq)` et cetera should be removed/replaced by corresponding `convert` methods since type conversion is much more versatile in Julia.
If you agree with me, I'll fix them and add more commits to this pull request.
=> add `convert` to a byte sequence from bio sequences

src/seq/Seq.jl
I'm inclined believe that appending the `Base.` prefix is a better solution (ref: #96).
=> import hash from Base

src/align/anchors.jl, test/align/TestAlign.jl
If I read [this comment] (https://github.com/BioJulia/Bio.jl/blob/93a83c11edcff057849ea84e41d5aa82ce308131/src/align/anchors.jl#L77-Lundefined) correctly, this would be the intended behavior.
=> fix firstref and lastref

src/Bio.jl, src/seq/Seq.jl, src/seq/aminoacid.jl, src/seq/nucleotide.jl, src/util/Util.jl, src/util/windows.jl, test/TestFunctions.jl, test/align/TestAlign.jl, test/intervals/TestIntervals.jl, test/runtests.jl, test/seq/TestSeq.jl, test/util/TestUtil.jl
Modified slightly the sliding windows code of @kdmurray91 - instead of requireing a vector of something, it is parametric and works fo any type T (instead of Vector{T}) that implements the sub() method. I added the sub() method for nucelotide sequences too - which is the same as constructing a subsequence with `seq[x:y]`. 
A rebase was done so thought it was easier to just open a new PR and then close both, than try and merge or push back to the origional PR. But @kdmurray91's contribution is reflected in the commit history.
=> Sliding windows - redux

docs/src/man/seq.md, src/seq/geneticcode.jl, src/seq/nucleotide.jl, test/seq/runtests.jl
This will fix #133 and try to resolve ambiguous code more aggressively.
The previous code attempted to translate ambiguous codon only when the first and second nucleotides have no ambiguity. In this change, three nucleotides will have same weight to determine a translated amino acid and types of ambiguity of nucleotides are considered (for example, `rna"GAN"` can be translated to D or E but `rna"GAY"` can be uniquely translated to D because Y is C or U in IUPAC; we do it if possible).
TODO:
=> fix genetic code

docs/src/man/alignments.md, src/align/anchors.jl, test/align/runtests.jl
This adds constructors that create `AlignedSequence` from `BioSequence`s with gap symbols.
I still need to add tests and docs, but it's time to go to bed :sleeping:.
@kescobo Does this meet your demand?
=> add constructors of AlignedSequence from BioSequences

REQUIRE, src/Bio.jl, src/tools/blast/Blast.jl, src/tools/blast/README.md, src/tools/blast/blastcommandline.jl, test/tools/runtests.jl
Bio.jl needs a way to run BLAST and other command line tools commonly used in biology applications, taking inputs and capturing outputs in Bio.jl formats. 
With Blast+ installed on users' system:
**Input**
**Output**
=> Blastwrapper

.travis.yml
This would be necessary to pass tests of the BLAST wrapper.
=> install NCBI BLAST+ before running Travis CI

src/seq/bioseq.jl
This removes `@encode_seq` macro, which is not used anymore. I will merge this soon.
=> remove encode_seq macro

REQUIRE, src/Bio.jl, src/precompile.jl
I'm try to precompile Bio.jl module locally. Precompiling greatly cut down the load time especially for parsers.
**startup.jl**
```julia
println("--- loading ---")
tic()
using Bio.Seq
using Bio.Align
using Bio.Intervals
using Bio.Structure
toc()
println("--- running ---")
tic()
for rec in open("sample.bed", BED) end
for rec in open("sample.fasta", FASTA) end
for rec in open("sample.fastq", FASTQ) end
toc()
```
**Not precompiled (master)**
```
~/.j/v/Bio ((eeece67...)|…) $ julia startup.jl
--- loading ---
elapsed time: 7.950095168 seconds
--- running ---
elapsed time: 9.586036993 seconds
```
**Precompiled**
```
~/.j/v/Bio (precompile|…) $ julia startup.jl
--- loading ---
elapsed time: 1.373317087 seconds
--- running ---
elapsed time: 5.049919548 seconds
```
I guess there is still more room …
=> Precompile

src/seq/kmer.jl
(Now I'm splitting #152 into several pull requests).
This will add `eltype` for the `Kmer` type. I believe nobody is against this change, so I will merge this soon.
=> define eltype for Kmers

docs/src/man/seq.md, src/seq/Seq.jl, src/seq/aminoacid.jl, src/seq/nucleotide.jl, test/seq/runtests.jl
(This was a part of #152.)
This pull request adds `iscompatible(x, y)` function for biological symbols. This function returns `true` if and only if two symbols are compatible with each other. For example, `DNA_A == DNA_N` is `false` but `iscompatible(DNA_A, DNA_N)` is `true` because `DNA_N` may be `DNA_A`.
Bikeshedding: Is there more suitable name to native English speakers than `iscompatible`?
=> add iscompatible

src/align/pairwise/algorithms/banded_needleman_wunsch.jl
This overwriting has killed tests on the banded Needleman-Wunsch algorithm on Julia v0.5.
=> rename internal macros to avoid overwriting others

docs/src/man/seq.md, src/seq/Seq.jl, src/seq/search/exact.jl, test/seq/runtests.jl
This adds `search` and `rsearch` methods for sequences. These works like `Base.search`/`Base.rsearch` for strings, but match ambiguous symbols, too. In the following example, the target sequence `dna"ACGNATT"` has an ambiguous nucleotide `DNA_N` at the 4th symbol, which matches any character in the queries: 
```julia
julia> using Bio.Seq
julia> search(dna"ACGNATT", dna"ACG")
1:3
julia> search(dna"ACGNATT", dna"CGT")
2:4
julia> search(dna"ACGNATT", dna"GGA")
3:5
```
I'm now planning to implement three kinds of sequence search utils:
1. Exact search (this pull request)
2. Approximate search that allows errors (substitution/insertion/deletion) up to `k` (#153)
3. Regular expression search (#143)
The first one (this pull request) is ready to review. The second one is not yet a pull request, …
=> Exact search/rsearch for sequences.

docs/make.jl, docs/mkdocs.yml, docs/src/assets/friendly.css, docs/src/man/alignments.md, docs/src/man/seq.md
I'm now trying to improve the style of our documents. 
Here are screenshots:
**Current**
**New**
Pending issues are:
*  Syntax highlighter improvement: https://bitbucket.org/birkenfeld/pygments-main/pull-requests/594/fix-julialexer-and-juliaconsolelexer/diff
* Stylistic docstrings: https://github.com/MichaelHatherly/Documenter.jl/issues/48
=> improve style of docs

docs/mkdocs.yml, docs/src/assets/custom.css
Wider space before and after headings, narrower space before codes.
=> tweak spacing of HTML docs

docs/src/man/seq.md, src/seq/Seq.jl, src/seq/aminoacid.jl, src/seq/fasta.jl, src/seq/fastq.jl, src/seq/nucleotide.jl, src/seq/symbolrange.jl, test/seq/runtests.jl
This pull request includes three topics:
1. Introduce `SymbolRange` type which is similar to `Base.UnitRange` but specialized for our biological symbols.
2. Make symbol arithmetic cyclic; for example, `DNA_A + 16` is `DNA_A`, not `DNA_INVALID`.
3. Make `show(io::IO, Nucleotide|AminoAcid)` more informative; for example `show(AA_A)` shows `AA_A` not `A`.
2 depends on 1, and 3 is a thing I want for a long time.
```
julia> seq = dna"ACGT"
4nt DNA Sequence:
ACGT
julia> seq[1]  # if we show 'A', we cannot see it from RNA and amino acid
DNA_A
```
If you need one-letter representation, you can call `print` instead of `show`.
=> SymbolRange, cyclic arithmetic, and more informative `show` method.

src/intervals/strand.jl, test/intervals/runtests.jl
Like #190, this pull request makes `show(::Strand)` more informative when used in REPL and so on. Docstrings and tests are also added.
=> make show(strand) more informative

docs/src/man/reading.md, src/seq/Seq.jl, src/seq/fasta.jl, test/seq/runtests.jl
This restores the `FASTASeqRecord` type alias, which I removed without careful thought.
I think `FASTAMetadata` will not be used by users because `FASTASeqRecord` is able to create a FASTA record for serialization. So, I removed it from the exported list (#207).
I will fix interfaces for other formats very soon.
=> fix FASTA writer interfaces

src/seq/Seq.jl, src/seq/fastq.jl, test/seq/runtests.jl
As per `FASTASeqRecord`, this makes it easier to create FASTQ sequence records that can be serialized using `FASTQWriter`.
=> fix FASTQ writer interfaces

src/intervals/Intervals.jl, src/intervals/bed.jl, test/intervals/runtests.jl
Like FASTAWriter and FASTQWriter, this adds BEDWriter and its interfaces for serializing intervals in BED format.
=> add BEDWriter

.travis.yml
Allow nightly builds but let them fail without affecting our build status. So we can see how Bio.jl does on the cutting edge of julia.
=> Added nightly builds as an allowed failiure

docs/mkdocs.yml, docs/src/assets/sidecar.js
Thought it would be cool for readers of docs if it was possible to have Gitter sidecar in there, so if they see something and have questions, they can immediately pop it open and talk to someone.
I believe I've done this correctly with mkdocs, _but_ I'm not 100% sure, and we can't see how it affects the page until we merge to master.
=> Added sidecar to docs

test/tools/runtests.jl
This temporarily disable the BLAST tests on Windows in order to pass AppVeyor on Windows.
=> temporarily disable BLAST tests on Windows

REQUIRE, src/phylo/Phylo.jl, src/phylo/dating.jl, test/phylo/runtests.jl
This PR adds a Dating submodule to Phylo. Initially it contains a simple procedure I designed for a larger software project on my PhD, which returns an estimation of the coalescence time between two sequences, based on assumptions formalised by modelling mutation accumulation between sequences as a binomial process.
=> Added the Dating submodule to Phylo.

docs/src/man/seq.md, src/seq/Seq.jl, test/seq/runtests.jl
Very simple PR.
Sometimes if a user is dealing with individual nucleotides, or iterating a seq nucleotide by nucleotide, it would be useful to be able to use the isambiguous method.
=> Export isambiguous from Seq module.

src/precompile.jl, src/seq/fastq.jl, src/seq/quality.jl, test/seq/runtests.jl
Closes #242.
This branch fixes the problem by requiring that exactly one quality encoding is provided to the FASTQParser, so no inference is done to determine the quality encoding.
An alternative solution would infer the quality encoding for all sequences in the file at once, but then they could not be parsed record by record.
=> Fix fastq quality encoding inference

src/seq/fasta.jl, src/seq/fastq.jl, test/seq/runtests.jl
I've somewhat been astonished by this because there is no way to free resources of opened files without it.
=> add close for FASTAParser and FASTQParser

docs/src/man/labelledmatrix.md, src/Bio.jl, src/util/Util.jl, src/util/labelledmatrix.jl, test/util/labelledmatrix.jl, test/util/runtests.jl
As talked about on gitter, this PR adds a parser for the common LSM format used to store e.g. distance matrices. The parser is currently a little ad-hoc, and adapted from @bicycle1885's substitution matrix parsers.
I will also attach a commit that removes that parser, and uses the `readlsm` function included here.
This is ready to review
=> Add labelled square matrix parser

docs/src/man/seq.md, src/seq/Seq.jl, src/seq/randseq.jl, test/REQUIRE, test/seq/runtests.jl
This adds random sequence generators for DNA, RNA, and amino acids. At the moment, the only available generator is `StationaryGenerator`, but the interface is extensible so that we can add more elaborate generators like HMM or RNN.
=> add random sequence generators

docs/src/man/reading.md
This simply adds a quick example to show how to parse a FASTQ to the IO docs.
=> Add example to parsing of fastq sequences

src/seq/deprecated.jl
We should have removed these functions before the release of Bio.jl 0.3.
=> remove deprecated names

src/seq/Seq.jl, src/seq/deprecated.jl, src/seq/sequence.jl, test/seq/runtests.jl
I'm not completely sure but `ispalindromic` would be more common than `ispalindrome`. More generally, I'd like to think that `XXX` of `isXXX` should be an adjective word if possible.
=> rename ispalindrome to ispalindromic

src/seq/bioseq.jl
With this change, `reverse_complement` became ~7x faster.
Before (master):
```
julia> srand(1234);
julia> seq = randdnaseq(10_000)
10000nt DNA Sequence:
GTGCTTACAGGAATGACGATTTTTTAACACTCAAACGCCTAGCC…TGACTAGCCATTTGTCACCCAACACGGGCGAGCGGGCATGTGTA
julia> @benchmark reverse_complement(seq)
BenchmarkTools.Trial:
samples:          10000
evals/sample:     1
memory estimate:  5.02 kb
allocs estimate:  2
minimum time:     38.07 μs (0.00% GC)
median time:      38.37 μs (0.00% GC)
mean time:        42.33 μs (0.00% GC)
maximum time:     864.49 μs (0.00% GC)
```
After:
```
julia> srand(1234);
julia> seq = randdnaseq(10_000)
10000nt DNA Sequence:
GTGCTTACAGGAATGACGATTTTTTAACACTCAAACGCCTAGCC…TGACTAGCCATTTGTCACCCAACACGGGCGAGCGGGCATGTGTA
julia> @benchmark …
```
=> improve the performance of reverse_complement

src/seq/kmer.jl, test/seq/runtests.jl
Before (master):
```
julia> @benchmark gc_content($(DNAKmer("ACGT"^8)))
BenchmarkTools.Trial:
samples:          10000
evals/sample:     992
memory estimate:  0.00 bytes
allocs estimate:  0
minimum time:     37.00 ns (0.00% GC)
median time:      47.00 ns (0.00% GC)
mean time:        47.93 ns (0.00% GC)
maximum time:     1.94 μs (0.00% GC)
```
After:
```
julia> @benchmark gc_content($(DNAKmer("ACGT"^8)))
BenchmarkTools.Trial:
samples:          10000
evals/sample:     1000
memory estimate:  0.00 bytes
allocs estimate:  0
minimum time:     6.00 ns (0.00% GC)
median time:      6.00 ns (0.00% GC)
mean time:        6.02 ns (0.00% GC)
maximum time:     60.00 ns (0.00% GC)
```
=> improve the performance of gc_content(::Kmer)

src/seq/predict.jl
This improves the performance of parsing a FASTA file when the sequence is a long DNA or RNA sequence like chromosomal sequences.
Benchmark results of parsing chromosome 1 of human are:
Before (master):
```
6.017943 seconds (34.78 M allocations: 801.361 MB, 1.46% gc time)
```
After:
```
3.909558 seconds (34.78 M allocations: 801.361 MB, 2.55% gc time)
```
=> improve the performance of sequence type prediction

src/seq/bioseq.jl, src/seq/nucleotide.jl, test/seq/runtests.jl
This improves the performance of encoding an ASCII string into a DNA/RNA sequence, which also improves the performance of parsing a FASTA file.
Before (#275):
```
3.909558 seconds (34.78 M allocations: 801.361 MB, 2.55% gc time)
```
After:
```
3.013747 seconds (34.78 M allocations: 801.361 MB, 3.01% gc time)
```
=> improve the performance of encoding ASCII string

src/seq/bioseq.jl, test/seq/runtests.jl
@bicycle1885 - Implemented your post merge suggestions :+1: 
* Added sequence length checking behaviour to `seqmatrix`.
* Added tests of throw cases.
* Loosening the type constraint of `vseq` to `AbstractVector{BioSequence{A}}`.
* `major` is now just a parameter, not an optional one.
=> Extra refinement to `seqmatrix`

src/seq/sequence.jl
This forces the Julia compiler to inline functions related to sequence iterator. I don't know why but it significantly improves the performance if iteration. Julia 0.5 RC3 seems to have some regressions here.
```julia
using Bio.Seq
using BenchmarkTools
function foo(seq)
n = 0
for i in 1:endof(seq)
n += seq[i] == DNA_A
end
return n
end
function bar(seq)
n = 0
for i in 1:endof(seq)
@inbounds n += seq[i] == DNA_A
end
return n
end
function baz(seq)
n = 0
for nt in seq
n += nt == DNA_A
end
return n
end
const seq = randdnaseq(10000)
println(@benchmark foo($seq))
println(@benchmark bar($seq))
println(@benchmark baz($seq))
```
Before:
```
BenchmarkTools.Trial:
samples:          10000
evals/sample:     1
memory estimate:  0.00 bytes
allocs estimate: …
```
=> force inlining of sequence iterator

src/intervals/bed.jl, test/TestFunctions.jl, test/intervals/runtests.jl
This PR adds a function `intempdir` that lets a block of code (as an anonymous function) happen in a temp directory that gets created and deleted automagically. I use this function to stop the `Interval` tests from leaking BED files into the test sources directory.
=> Make tests that create files happen in temp dir

src/align/hts/bam/record.jl, src/align/hts/sam/record.jl, src/intervals/Intervals.jl, src/intervals/interval.jl, test/intervals/runtests.jl
This adds `leftposition` and `rightposition` accessor functions to the `Interval` type. Currently, we extend the `Base.first` and `Base.last` functions to access left/rightmost position of an interval. However, `Base.first` and `Base.last` already have well-defined semantics in the standard library and I think we should not abuse them for the interval types. Along with #297, we can always use the `leftposition` and `rightposition` functions for interval-like objects.
=> add left/rightposition accessors to Interval

src/seq/bioseq.jl
Modifications to the majority vote algorithm greatly improving performance by removing branching/special cases, and greatly decreasing the amount of memory allocation.
Benchmarks:
Before:
```julia
julia> @benchmark consensus = majorityvote(sequences)
BenchmarkTools.Trial: 
samples:          4
evals/sample:     1
memory estimate:  537.20 mb
allocs estimate:  6376133
minimum time:     1.29 s (6.60% GC)
median time:      1.37 s (10.87% GC)
mean time:        1.37 s (10.95% GC)
maximum time:     1.46 s (14.98% GC)
julia> @time consensus = majorityvote(sequences)
1.279496 seconds (6.38 M allocations: 537.197 MB, 7.12% gc time)
398508nt DNA Sequence:
GCTACTCGTCGTGTCGAAGTCGGCCGCGGCGCGTTTGTA…AGAATCCAAAATACAACGGCAATGGAAACAATAAATTAA
```
After:
```julia …
```
=> Majority vote improvement

docs/src/man/var.md, src/var/Var.jl, src/var/mutation_counting.jl, test/var/runtests.jl
Adds an `is_mutation` method for seqmatrices. 
Produces boolean matrixes indicating which positions are mutated and which are not for every pairwise combination of sequences. 
This is useful for e.g. if you're doing sliding window distance computations or mutation counting computations to find hotspots across sequences, regions of high/low divergence, and so on, as all you need to do is slide across these boolean matrices and so `sum` operations.
=> `flagmutations` for seqmatrixes

src/align/hts/bam/record.jl, test/align/runtests.jl
This makes `qualities(::BAMRecord)` return `Vector{Int8}` rather `Vector{UInt8}`. This will improve interoperations between FASTQ and BAM. Also, I believe 127 (= `typemax(Int8)`) is large enough to cover the range of Phred scores.
=> make qualities(::BAMRecord) return a vector of Int8

src/align/Align.jl, src/align/alignedseq.jl, src/align/alignment.jl, src/align/deprecated.jl, src/align/pairwise/alignment.jl, test/align/runtests.jl
I don't remember why I decided this argument order, but now it looks a little bit strange to me. Generally, the container argument should come first if possible.
=> swap argument order of seq2ref and ref2seq

docs/src/man/reading.md, src/align/hts/bam/reader.jl, src/align/hts/bam/writer.jl, src/align/hts/sam/reader.jl, src/align/hts/sam/writer.jl, test/align/runtests.jl
I added SAM/BAM docs and a new constructor of `SAMReader` that takes a SAM header as its argument as per `BAMWriter`.
=> add docs on HTS tools

src/align/hts/bam/record.jl, src/align/hts/sam/record.jl, test/align/runtests.jl
This fixes the implementation of `ismapped` according to the specs of the SAM/BAM file format:
> Bit 0x4 is the only reliable place to tell whether the read is unmapped.
=> fix ismapped

docs/src/man/seq.md, src/seq/bioseq.jl, test/seq/runtests.jl
We no longer need to add the `Seq.` prefix to `complement` and `complement!` since the standard library of Julia dropped these function names. I also stopped using the `@generated` macro to define `complement!`.
=> add touch-ups to complement and complement!

src/IO.jl
This fixes the definition of the `Base.iteratorsize` trait.
=> fix Base.iteratorsize for AbstractReader

REQUIRE, src/align/hts/bam/reader.jl
This makes it possible to read a CRAM file via samtools as follows:
```julia
reader = BAMReader(open(`samtools view -u data.cram`)[1])
```
It may be worth adding `CRAMReader` to Bio.jl that wraps this idiom.
=> bump BGZFStreams dependency

src/align/hts/bam/reader.jl, src/align/hts/sam/reader.jl, test/align/runtests.jl
This simplifies the `Base.show` method for `SAM/BAMReader` because printing all contig names often fills a terminal window.
=> simplify the show method of SAM/BAMReader (and fix a bug)

src/align/hts/bam/record.jl, src/align/hts/hts.jl, src/align/hts/sam/record.jl, test/align/runtests.jl
This unifies the show methods for SAM and BAM records and implements a single line printer.
=> clean up SAM/BAMRecord printing

src/align/hts/bam/reader.jl, test/align/runtests.jl
This simple patch significantly (~15%) improves the performance of reading BAM records.
```julia
using Bio.Align
let
reader = open(BAMReader, "GSE25840_GSM424320_GM06985_gencode_spliced.bam")
record = BAMRecord()
@time while !eof(reader)
read!(reader, record)
end
close(reader)
end
#=
~/.j/v/Bio (master|…) $ julia5 test.jl
15.774832 seconds (63.40 M allocations: 977.437 MB, 1.33% gc time)
~/.j/v/Bio (master|✚1…) $ julia5 test.jl
13.658773 seconds (22.08 M allocations: 346.885 MB, 1.59% gc time)
=#
```
=> make BAMReader type-stable

src/align/hts/bam/intersect.jl
An unmapped record may have mapped position of its mate read. This fixes the
behavior of `isoverlapping` so that a record does not need to be mapped to
overlap a genomic range as per samtools view.
=> do not check ismapped when checking isoverlapping

src/align/hts/bam/intersect.jl, test/align/runtests.jl
This separates an iteration state from the `BAMIntersectionIterator`.
=> make BAMIntersectIterator stateless

src/align/hts/bam/reader.jl, src/align/hts/bam/record.jl, src/align/hts/bam/writer.jl
This change reduces the number of read/writer operations when reading/writing BAM
records from a file, which improves the performance of BAM I/O.
```julia
using Bio.Align
let
reader = open(BAMReader, "GSE25840_GSM424320_GM06985_gencode_spliced.bam")
record = BAMRecord()
@time while !eof(reader)
read!(reader, record)
end
close(reader)
end
#=
~/.j/v/Bio (master|…) $ julia5 test.jl
13.365396 seconds (22.08 M allocations: 346.885 MB, 0.15% gc time)
~/.j/v/Bio (master|…) $ julia5 test.jl
13.287189 seconds (22.08 M allocations: 346.885 MB, 0.15% gc time)
v.s.
~/.j/v/Bio (reorg-bamrecord|…) $ julia5 test.jl
12.702789 seconds (1.42 M allocations: 31.639 MB, 0.04% gc time)
~/.j/v/Bio (reorg-bamrecord|…) $ julia5 test.jl
12.796799 seconds (1.42 M allocations: 31.639 MB, 0.05% gc time)
=#
```
=> re-organize BAMRecord fields

src/util/windows.jl, src/var/distances.jl, src/var/mutation_counting.jl, test/var/runtests.jl
A PR that allows you to compute genetic distances between sequences using a sliding window. Not the most optimal, but needed for some work being done this week here. Eventually this design will be greatly improved by PR #334.
=> Sliding window distance computation

REQUIRE
Because Julia 0.5 is already released.
=> require Julia 0.5 or later

docs/src/man/phylo.md, src/phylo/Phylo.jl, src/phylo/branch_basics.jl, src/phylo/manipulation.jl, src/phylo/metadata.jl, src/phylo/phylogeny.jl, src/util/indexing.jl, test/phylo/runtests.jl
This is a very simple change to Phylo. It alters the branchlength and branchlength! methods so as when people create immutable types to act as branch metadata, if they just define a branchlength and branchlength! method for that type, then getting and setting the branch length for any phylogeny type should "just work".
=> Refactored the branchlength setting and getting API.

REQUIRE, src/tools/blast/BLAST.jl, src/tools/blast/blastcommandline.jl
Per request from @bicycle1885 - I altered the BLAST results parser to use EzXML rather than LightXML. This works, though I'm not sure that using XPath queries all over the place is the most efficient approach. Happy to incorporate any feedback if there's a better way.
I added EzXML to REQUIRE, but did not remove LightXML, since I think there's something else that still relies on it.
=> Blast xml fix

src/phylo/dating.jl, test/phylo/runtests.jl
Adds some methods which mean the divergence time estimation module in Phylo can do a little more than it did previously. Specifically, you can give an array of mutation counts / genetic distances to a method of `coaltime` and get an array of time estimates returned.
=> Added more to divergence time estimation

src/structure/model.jl
This fixes a small error when residue names are less than 3 characters in length by making sure to compare the unstripped names.
Will merge soon unless there are any objections.
=> fix resname spacing bug

src/StringFields.jl, src/intervals/gff3/gff3.jl
These changes fix the concerns raised in issue #369, in preparation for julia 0.6: namely that you cannot access the raw bytes of a string using `string.data` anymore.
=> Fix issue #369

src/align/hts/sam/reader.jl
Fix a bug when reading SAM files with a large (>128KiB) header section (closes #373).
=> fix the SAM header parser (#373)

.travis.yml, README.md
This deactivates Coveralls. We already use two coverage tracking systems: [codecov](https://codecov.io/gh/BioJulia/Bio.jl) and [coveralls](https://coveralls.io/github/BioJulia/Bio.jl). This is redundant and I think it would be better to remove one of them. To my eyes, the interfaces of Coveralls are less intuitive and its reporting is [too verbose](https://github.com/BioJulia/Bio.jl/pull/378). [Automa.jl](https://github.com/BioJulia/Automa.jl) and [EzXML.jl](https://github.com/bicycle1885/EzXML.jl) have already dropped Coveralls for this reason.
=> deactivate Coveralls

src/Bio.jl, src/align/Align.jl, src/align/pairwise/result.jl, src/declare.jl, src/phylo/Phylo.jl, src/structure/Structure.jl, src/structure/pdb.jl, src/structure/spatial.jl, src/var/Var.jl, src/var/distances.jl
This resolves a method name conflict that happens between sub-modules of Bio.jl. The `distance` function is defined in three sub-modules: `Bio.Align`, `Bio.Structure` and `Bio.Var`. This is problematic when we call `using` two of them:
```
julia> using Bio.Align, Bio.Var
INFO: Recompiling stale cache file /Users/kenta/.julia/lib/v0.5/Bio.ji for module Bio.
INFO: compiling FASTA
julia> distance
WARNING: both Var and Align export "distance"; uses of it in module Main must be qualified
ERROR: UndefVarError: distance not defined
```
This patch declares the `distance` function in `Bio` and extends it in each submodule. If this approach works well, I'd like to use it more pervasively in Bio.jl.
CC: @Ward9250 and @jgreener64.
=> declare Bio.distance to resolve the method name conflict

docs/src/man/structure.md
Add a table of atom/residue selectors to the `Bio.Structure` docs, and link to some benchmarks.
=> Selector table in Bio.Structure docs

REQUIRE, src/intervals/Intervals.jl
Because `RGB` is actually defined in ColorTypes.jl.
=> require ColorTypes.jl instead of Colors.jl

src/Ragel.jl, src/align/Align.jl, src/align/alignedseq.jl, src/align/hts/bam/bai.jl, src/align/hts/bam/intersect.jl, src/align/hts/bam/reader.jl, src/align/hts/bam/writer.jl, src/align/hts/hts.jl, src/align/hts/sam/reader.jl, src/align/pairwise/alignment.jl, src/align/submat.jl, src/declare.jl, src/intervals/Intervals.jl, src/intervals/bbi/intersection.jl, src/intervals/bbi/reader.jl, src/intervals/bbi/writer.jl, src/intervals/gff3/reader.jl, src/intervals/interval.jl, src/intervals/intervalcollection.jl, src/intervals/intervalstream.jl, src/seq/Seq.jl, src/seq/demultiplexer.jl, src/seq/fasta/reader.jl, src/seq/nmask.jl, src/seq/search/re.jl, src/structure/Structure.jl, src/structure/model.jl, src/tools/blast/BLAST.jl, src/tools/blast/blastcommandline.jl, src/util/windows.jl
The larger our package is, the harder it is to identify names imported from other packages. The reason is mainly because the `using` syntax hides the origin of names and we (at least I) do not have good memory enough to remember all unqualified names.
This pull request will fix the problem by removing `using` used under the `src` directory. The rules are:
1. Do not use `using` to import names from other modules.
2. Use `import` to use other modules.
3. Import names from other modules only when the names are used repeatedly.
4. Use `imoprtall Bio` to import and extend methods shared among submodules of `Bio`.
Currently, I fixed `Bio.Seq`, `Bio.Align`, and `Bio.Intervals` only. I'm going to tidy up other modules if you agree with me.
=> Tidy import

src/align/submat.jl, test/TestFunctions.jl, test/align/runtests.jl, test/intervals/runtests.jl, test/seq/runtests.jl, test/structure/runtests.jl, test/tools/runtests.jl, test/util/labelledmatrix.jl
`Pkg.dir` won't point to the correct path when the package is installed in a non-standard location.
=> replace Pkg.dir calls with joinpath(dirname(...))

README.md
I'd like to encourage users to use Discourse for technical questions. This is because Gitter has no threads and it is often difficult to distinguish interesting replies from others. Also, Discourse will catch more eyes from the Julia community, so I guess it may strengthen our presence in the community.
=> encourage users to use Discourse for technical questions

src/intervals/index/bgzfindex.jl
The previous commit (049ed2df1780b0218f00db63bbb73ef3c1a13249) fixes a special
case but this will fix the problem fundamentally.
=> fix linear index access of BAM, fundamentally

docs/mkdocs.yml
This is a simple change to an error which is preventing the update of our online documentation, following re-organization of the `Seq` module.
I'll leave this up for an hour but since it's simple I want to merge it ASAP so as our online manual gets updated.
=> Fix to documentation

test/var/runtests.jl
I didn't notice but large amounts of tests of Bio.Var are inside a block comment. This seems to be introduced in this commit: https://github.com/BioJulia/Bio.jl/commit/3ed91d20d140b2385aa5673bbf949700eb62fec8. Unfortunately, some tests didn't pass and I'm not sure how I should fix them. So, I narrowed the range of the comment and fixed a few test I could.
@Ward9250 Could you take care of that after change?
=> fix some Bio.Var tests

NEWS.md, docs/src/man/var.md, src/seq/Seq.jl, src/seq/minhash.jl, src/var/Var.jl, src/var/mash.jl, test/seq/runtests.jl, test/var/runtests.jl
This is a PR for an idea [I brought up months ago in gitter](https://gitter.im/BioJulia/Bio.jl?at=584c96b1c29531ac5d4917e2). I'd like to add a small module to calculate the [MASH distance](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0997-x) between two genomes. 
Briefly, the theory is that you generate a hash for all kmers of size `k`, but only store a "bottom sketch" of a particular genome of size `s` - that is the `s` smallest hashes. If you store the hashes in sorted order, you only need to check if each subsequent hash is larger than a single value, so this is quite fast. The genome distance for two genomes is then essentially the [Jaccard index](https://en.wikipedia.org/wiki/Jaccard_index) of the minhashes, with some additional modification to account for the …
=> Genomic Distances using MASH

src/structure/pdb.jl, src/structure/spatial.jl, test/structure/runtests.jl
I've been sitting on this for a bit but forgot to push - it's a small change that speeds up PDB parsing by using individual functions for each entry type.
Parsing 1CRN goes from ~2.7 ms to ~1.4 ms, making Bio.jl the fastest PDB parser I have tested (see https://github.com/jgreener64/pdb-benchmarks).
I think it should go in before BioJulia v0.5 and the great repo switch.
Ready to review.
=> Bio.Structure parsing speedup

src/seq/Seq.jl, test/seq/runtests.jl
Since the ACG{T,U} constants are exported, I feel ACGTN should be. That, and I was going mad trying to work out why I coudn't see it in the repl.
K
=> Export the ACGTN constant

src/seq/demultiplexer.jl
Removes the less optimised hamming_distance function created for this package.
@bicycle1885, there is also a hamming distance implementation in [Bio.Align](https://github.com/BioJulia/Bio.jl/blob/master/src/align/pairwise/algorithms/hamming_distance.jl). Would it be wise to remove some of the duplication of such functions as part of #425?
=> Use Bio.Seq.mismatches in demulitplexer

docs/src/man/seq/sequences/bioseq.md, src/seq/Seq.jl, src/seq/alphabet.jl, src/seq/bioseq/conversion.jl, src/seq/bioseq/operators.jl, test/seq/runtests.jl
This PR will add promotion to biological sequences in order to allow completion of #436.
Essentially the rule will be if you have DNA or RNA sequences and want to promote them to the same type, they will be promoted to the alphabet that is capable of representing all the possible elements, so `promote_rule(DNAAlphabet{2}, DNAAlphabet{4})` will return `DNAAlphabet{4}`, as `DNAAlphabet{4}` is the one that is capable of representing all elements of `DNAAlphabet{2} and DNAAlphabet{4}`.
=> Promotion for DNA/RNA sequences

docs/src/man/reading.md, src/align/bam/record.jl, src/align/sam/record.jl, test/align/runtests.jl
According to the SAM specs:
> For each read/contig in a SAM file, it is required that one and only one line associated with the
read satisfies ‘FLAG & 0x900 == 0’. This line is called the primary line of the read.
I found this is sometimes useful.
=> add isprimary for SAM.Record and BAM.Record

src/seq/composition.jl, src/seq/eachkmer.jl, src/seq/kmer.jl
On my machine, `composition` is now ~20-30% faster for short kmers (e.g. 4-8).
```
~/.j/v/B/benchmarks (faster-eachkmer|…) $ julia
_
_       _ _(_)_     |  A fresh approach to technical computing
(_)     | (_) (_)    |  Documentation: http://docs.julialang.org
_ _   _| |_  __ _   |  Type "?help" for help.
| | | | | | |/ _` |  |
| | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
_/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin16.4.0
julia> using BenchmarkTools
julia> using Bio.Seq
INFO: Recompiling stale cache file /Users/kenta/.julia/lib/v0.5/Bio.ji for module Bio.
INFO: compiling FASTA
INFO: compiling FASTQ
INFO: compiling old FASTA
INFO: compiling BED
INFO: compiling GFF3
INFO: compiling SAM
INFO: compiling VCF
WARNING: Method definition require(Symbol) in …
```
=> implement a faster and simpler eachkmer

src/structure/pdb.jl, test/structure/runtests.jl
This test of the PDB can actually fail if no entries were obsoleted recently.
=> Remove PDB update test that may fail

REQUIRE
Doesn't look like Iterators is ever imported
=> Remove Iterators.jl dependency (not used)

README.md
I think some people are conflating Bio.jl with the whole BioJulia project, and might be put off by the warning if they land on the Bio.jl repo. See for instance https://discourse.julialang.org/t/finding-new-packages-and-docs/10417/7.
This clarifies the status of the project. I will merge in a day unless anyone objects.
=> Clarify status of project in readme
